# Generated by Django 3.2 on 2021-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnailUrl',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
