# Generated by Django 3.2 on 2021-05-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20210508_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnailUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
